### ISSUE TITLE
Ask user if he/she wants to use default params (post-test) 

### ISSUE THREAD

**Issue by badb** [golemfactory/golem-electron#110]
After test task is finished a suggested params values are sent back. 
We may want to display popup that asks user to choose those parameters or those that he/she may have already entered. 
We're not sure that it's a good ux, but maybe it's worth trying out. Better UX suggestions are welcomed.

**Comment by mdtanrikulu** [comment]
We can add a "remember choice" checkbox, if they want to keep use suggested parameters with their tasks.
Then we'll add this parameter to the settings if they'd like to close this "remember" feature. 
 

<img width="743" alt="screen shot 2017-10-02 at 13 02 13" src="https://user-images.githubusercontent.com/2774845/31074682-20df41d4-a772-11e7-88f6-33d9d818c6b7.png">

**Comment by jamuszyn** [comment]
We should change wording of this information, because parameters won't be "better", they will actually be taken from Blender file. So we should ask user if he would like to apply file settings from his file. We could also ask this before local test, just after task upload step, and in case if user agreed to apply settings from Blender file, just after local render test, fill the inputs for him.
