### ISSUE TITLE
golem overwrites output files for tasks with the same name

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#134]
if two tasks have the same task name eg. default "Golem Task", files of the first task will be overwritten by files from the second task. Golem is not warning user that tasks have the same names nor that user can lose  files.

**Comment by badb** [comment]
This issue was solved in [#1758](https://github.com/golemfactory/golem/pull/1758l) for single frame Blender tasks.
Results are still being overwritten for mulit-frames task. @mdtanrikulu has a good idea how to potentially solve it - create separate dictionary for multiframes task, make sure that directory is not overwritten. We should discuss this with our Blender testers to make sure it works well with their workflow.

**Comment by mdtanrikulu** [comment]
@jamuszyn is it possible to get user ideas about it?

**Comment by jamuszyn** [comment]
I think that additional research for this particular solution is not needed. Most of Blender users that we talked to and recorded workflow keep their files well organized. So creating nested folders with timestamps is a good solution for this issue.

**Comment by mdtanrikulu** [comment]
Resolved by golemfactory/golem#4037.
