### ISSUE TITLE
GUI empty on OSX 10.13.4

### ISSUE THREAD

**Issue by S1W** [golemfactory/golem-electron#323]
Found a (small) bug: When installing Golem beta and removing Golem testnet on OSX results in the new Golem GUI showing up empty. Restoring the beta version and have both versions on my Mac restores the windows contents of Golem Beta.

**Comment by mdtanrikulu** [comment]
Could you provide more information if possible? Screenshot of electron, logs of Golem?

**Comment by PetroJames** [comment]
I'm just realizing does the "golem" repo need to be running independently of the electron application for it to work? If so, this should be stated in the installation readme


I'm getting the same thing 

Backs-iMac-Pro:golem-electron digid$ npm start

> golem@0.1.10 start /Users/digid/Projects/golem-electron
> cross-env NODE_ENV=development electron .

Installing DevTools extensions...

2018-04-11 15:01:42.778 Electron[75964:10656099] *** WARNING: Textured window <AtomNSWindow: 0x7fe496947fa0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
DEFAULT_GETH undefined
GVA encoder info: AMD performance mode : 2
✓ React Developer Tools

✓ Redux DevTools

GVA encoder info: deleteSCDMetalContext : texture cache hits: 0, misses: 0
IPC Handlers created.
2018-04-11 15:01:56.017 Electron Helper[75969:10657923] Couldn't set selectedTextBackgroundColor from default ()

<img width="626" alt="screen shot 2018-04-11 at 3 04 27 pm" src="https://user-images.githubusercontent.com/35117670/38645652-acbd7942-3d99-11e8-9bc7-007c71541795.png">

**Comment by mdtanrikulu** [comment]
Hey @PetroJames, If you have Golem core from binary, you don't need to run it independently from electron. Electron will start golem automatically. 

But if you run golem on source as well, you should run golem first (with --mainnet flag if you want to run on mainnet.)

The problem here, seems like you're running electron from source, but you're just running electron side. You should open another terminal, go to electron path and run development server as well via
 
```npm run start:app```

when dev server is up, If you would like to run testnet, ```npm run start``` will be enough.
Or if mainnet, it gonna be ```npm run start:mainnet``` instead. 

And thanks for the feedback! I'll update readme with more detail.

**Comment by PetroJames** [comment]
Thanks, that worked!

**Comment by mdtanrikulu** [comment]
Welcome @PetroJames, happy to see it helped! 
Is the answer worked also for you @S1W ?

**Comment by mdtanrikulu** [comment]
I'm closing the issue. @S1W If it didn't work for you, feel free to open.
