### ISSUE TITLE
Balance indicator confusion

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/golem-electron#9]
Balance indicator shows our current GNT amount. ETH and USD sections are basically shows conversion of the GNT amount to the selected currency.

![balance-indicator](https://user-images.githubusercontent.com/2774845/27486516-24fab004-5831-11e7-957c-ba0acbbdb34a.gif)

The problem is in here; Golem system has both of GNT and ETH currencies. ETH currency is used for the gas price. To show ETH balance in the system, balance indicator UI must be rearranged or any other solutions are welcome.

**Comment by mattatgit** [comment]
![balances](https://user-images.githubusercontent.com/6858525/27819271-d0283d26-60dc-11e7-9b8e-bc8fd2c6b8bd.png)
This is what we're thinking to handle this. We'll expand this to a simple Atomic prototype & post it when ready.

**Comment by mattatgit** [comment]
Here's that prototype. To help make it clear that you are moving between balances or looking up conversions of those balances we've added slight up<>down & sideways animations to distinguish them. The "approximately X tx fees" i'm not in love with, but it does clarify things a bit.

Ultimately the whole system would be better if there was some automatic process in the background converting GNT to ETH & paying gas fees that way, rather than having to maintain 2 balances, which seems very clunky & likely to be a barrier to regular users.

https://app.atomic.io/d/2OoNiOI005rz
@mdtanrikulu @badb

**Comment by badb** [comment]
@mdtanrikulu We would like to review this issue. Please choose one of the solution suggested by Matt, or alternatively have two separet counters: default one with GNT & USD and hidden option with your gas budget ETH & USD. 
It may be a good idea to ask @ederenn which of this solution is most clear and functional for her.

**Comment by ederenn** [comment]
I'm preferring second solution showing some approximations. First one is rather confusing.

**Comment by mdtanrikulu** [comment]
Resolved #139.
